// Automatically generated by astro-icon
// 20e2b3178daae608c28f7dc13bfeea33841bbb16de34384dc2fd1401ee107e5f

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-left"
		| "arrow-right"
		| "flexibility"
		| "messageStar"
		| "stars"
		| "tick";
}